language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpspec run -v
